// Generated by gencpp from file ohm_mecanum_sim/KillRequest.msg
// DO NOT EDIT!


#ifndef OHM_MECANUM_SIM_MESSAGE_KILLREQUEST_H
#define OHM_MECANUM_SIM_MESSAGE_KILLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ohm_mecanum_sim
{
template <class ContainerAllocator>
struct KillRequest_
{
  typedef KillRequest_<ContainerAllocator> Type;

  KillRequest_()
    : name()  {
    }
  KillRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KillRequest_

typedef ::ohm_mecanum_sim::KillRequest_<std::allocator<void> > KillRequest;

typedef boost::shared_ptr< ::ohm_mecanum_sim::KillRequest > KillRequestPtr;
typedef boost::shared_ptr< ::ohm_mecanum_sim::KillRequest const> KillRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator1> & lhs, const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator1> & lhs, const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ohm_mecanum_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ohm_mecanum_sim/KillRequest";
  }

  static const char* value(const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KillRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ohm_mecanum_sim::KillRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ohm_mecanum_sim::KillRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OHM_MECANUM_SIM_MESSAGE_KILLREQUEST_H
