// Generated by gencpp from file ohm_mecanum_sim/Kill.msg
// DO NOT EDIT!


#ifndef OHM_MECANUM_SIM_MESSAGE_KILL_H
#define OHM_MECANUM_SIM_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <ohm_mecanum_sim/KillRequest.h>
#include <ohm_mecanum_sim/KillResponse.h>


namespace ohm_mecanum_sim
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace ohm_mecanum_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ohm_mecanum_sim::Kill > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::ohm_mecanum_sim::Kill&) { return value(); }
};

template<>
struct DataType< ::ohm_mecanum_sim::Kill > {
  static const char* value()
  {
    return "ohm_mecanum_sim/Kill";
  }

  static const char* value(const ::ohm_mecanum_sim::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::ohm_mecanum_sim::KillRequest> should match
// service_traits::MD5Sum< ::ohm_mecanum_sim::Kill >
template<>
struct MD5Sum< ::ohm_mecanum_sim::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ohm_mecanum_sim::Kill >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ohm_mecanum_sim::KillRequest> should match
// service_traits::DataType< ::ohm_mecanum_sim::Kill >
template<>
struct DataType< ::ohm_mecanum_sim::KillRequest>
{
  static const char* value()
  {
    return DataType< ::ohm_mecanum_sim::Kill >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ohm_mecanum_sim::KillResponse> should match
// service_traits::MD5Sum< ::ohm_mecanum_sim::Kill >
template<>
struct MD5Sum< ::ohm_mecanum_sim::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ohm_mecanum_sim::Kill >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ohm_mecanum_sim::KillResponse> should match
// service_traits::DataType< ::ohm_mecanum_sim::Kill >
template<>
struct DataType< ::ohm_mecanum_sim::KillResponse>
{
  static const char* value()
  {
    return DataType< ::ohm_mecanum_sim::Kill >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OHM_MECANUM_SIM_MESSAGE_KILL_H
