// Generated by gencpp from file ohm_mecanum_sim/Spawn.msg
// DO NOT EDIT!


#ifndef OHM_MECANUM_SIM_MESSAGE_SPAWN_H
#define OHM_MECANUM_SIM_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <ohm_mecanum_sim/SpawnRequest.h>
#include <ohm_mecanum_sim/SpawnResponse.h>


namespace ohm_mecanum_sim
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace ohm_mecanum_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ohm_mecanum_sim::Spawn > {
  static const char* value()
  {
    return "c1497b6490cf67615397a2f4c091d32a";
  }

  static const char* value(const ::ohm_mecanum_sim::Spawn&) { return value(); }
};

template<>
struct DataType< ::ohm_mecanum_sim::Spawn > {
  static const char* value()
  {
    return "ohm_mecanum_sim/Spawn";
  }

  static const char* value(const ::ohm_mecanum_sim::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::ohm_mecanum_sim::SpawnRequest> should match
// service_traits::MD5Sum< ::ohm_mecanum_sim::Spawn >
template<>
struct MD5Sum< ::ohm_mecanum_sim::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ohm_mecanum_sim::Spawn >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ohm_mecanum_sim::SpawnRequest> should match
// service_traits::DataType< ::ohm_mecanum_sim::Spawn >
template<>
struct DataType< ::ohm_mecanum_sim::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::ohm_mecanum_sim::Spawn >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ohm_mecanum_sim::SpawnResponse> should match
// service_traits::MD5Sum< ::ohm_mecanum_sim::Spawn >
template<>
struct MD5Sum< ::ohm_mecanum_sim::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ohm_mecanum_sim::Spawn >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ohm_mecanum_sim::SpawnResponse> should match
// service_traits::DataType< ::ohm_mecanum_sim::Spawn >
template<>
struct DataType< ::ohm_mecanum_sim::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::ohm_mecanum_sim::Spawn >::value();
  }
  static const char* value(const ::ohm_mecanum_sim::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OHM_MECANUM_SIM_MESSAGE_SPAWN_H
