// Generated by gencpp from file ohm_mecanum_sim/SpawnResponse.msg
// DO NOT EDIT!


#ifndef OHM_MECANUM_SIM_MESSAGE_SPAWNRESPONSE_H
#define OHM_MECANUM_SIM_MESSAGE_SPAWNRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ohm_mecanum_sim
{
template <class ContainerAllocator>
struct SpawnResponse_
{
  typedef SpawnResponse_<ContainerAllocator> Type;

  SpawnResponse_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , name()  {
    }
  SpawnResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnResponse_

typedef ::ohm_mecanum_sim::SpawnResponse_<std::allocator<void> > SpawnResponse;

typedef boost::shared_ptr< ::ohm_mecanum_sim::SpawnResponse > SpawnResponsePtr;
typedef boost::shared_ptr< ::ohm_mecanum_sim::SpawnResponse const> SpawnResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator1> & lhs, const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator1> & lhs, const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ohm_mecanum_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57f001c49ab7b11d699f8606c1f4f7ff";
  }

  static const char* value(const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57f001c49ab7b11dULL;
  static const uint64_t static_value2 = 0x699f8606c1f4f7ffULL;
};

template<class ContainerAllocator>
struct DataType< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ohm_mecanum_sim/SpawnResponse";
  }

  static const char* value(const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
"string name\n"
;
  }

  static const char* value(const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ohm_mecanum_sim::SpawnResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OHM_MECANUM_SIM_MESSAGE_SPAWNRESPONSE_H
